from app.nutrition.catalog import DEFAULT_MEALS, MealItem, estimate_macros_from_kcal
from app.nutrition.service import (
    MacroRange,
    MealRecommendation,
    NUTRITION_ACTIVITY_KIND,
    NUTRITION_CUSTOM_MEAL_KIND,
    NUTRITION_ENTRY_KIND,
    SPORT_MET,
    WEIGHT_ENTRY_KIND,
    activity_kcal_burned,
    daily_calorie_target_kcal,
    load_custom_meals,
    load_day_activity_entries,
    load_day_entries,
    load_weight_entries,
    macro_range_status,
    merged_meal_catalog,
    nutrition_dashboard_metrics,
    recommend_meals_for_targets,
    who_fat_loss_macro_targets,
)

__all__ = [
    "DEFAULT_MEALS",
    "MacroRange",
    "MealRecommendation",
    "MealItem",
    "NUTRITION_ACTIVITY_KIND",
    "NUTRITION_CUSTOM_MEAL_KIND",
    "NUTRITION_ENTRY_KIND",
    "SPORT_MET",
    "WEIGHT_ENTRY_KIND",
    "activity_kcal_burned",
    "daily_calorie_target_kcal",
    "estimate_macros_from_kcal",
    "load_custom_meals",
    "load_day_activity_entries",
    "load_day_entries",
    "load_weight_entries",
    "macro_range_status",
    "merged_meal_catalog",
    "nutrition_dashboard_metrics",
    "recommend_meals_for_targets",
    "who_fat_loss_macro_targets",
]

